name: flutter_basic_db
description: flutter_basic_db
version: 1.3.0
homepage: https://github.com/erlangs/flutter_basic_db
#publish_to: https://pub.dev
#publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sembast: '>=2.4.7+6'
  sembast_web: '>=2.1.0-1'
  sembast_sqflite: '>=1.0.0'
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:

  flutter_svg: ^2.0.7
  tekartik_app_flutter_sembast:
    path: ../tekartik_app_flutter_sembast
#    git:
#      url: https://github.com/tekartik/app_flutter_utils.dart
#      path: app_sembast
#      ref: dart2_3
#      version: '>=0.4.2'
  path_provider_macos:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
  tekartik_app_platform:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_platform
    version: '>=0.1.0'
  tekartik_app_roboto:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_roboto
      version: '>=0.1.0'
  path_provider:
  path:
  cv:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

flutter_intl:
  enabled: false
